version: "3.8"

services:
  lavalink:
    image: fredboat/lavalink
    container_name: lavalink
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins:/opt/Lavalink/plugins
    ports:
      - "${LAVALINK_PORT}:${LAVALINK_PORT}"
    environment:
      - _JAVA_OPTIONS=-Xmx512m
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
      - LAVALINK_PORT=${LAVALINK_PORT}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - lavalink

  zerotier:
    image: quay.io/zerotier/zerotier-signal:latest
    container_name: zerotier
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    environment:
      - ZT_NETWORKS=${ZEROTIER_NETWORK_ID}
      - ZT_AUTHTOKEN=${ZEROTIER_API_TOKEN}
    volumes:
      - zerotier-data:/var/lib/zerotier-one
    restart: unless-stopped
    depends_on:
      - lavalink

volumes:
  zerotier-data: