version: "3.8"

services:
  lavalink:
    image: fredboat/lavalink
    container_name: lavalink
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins:/opt/Lavalink/plugins
    ports:
      - "2333:2333"
    environment:
      - _JAVA_OPTIONS=-Xmx512m

  caddy:
    build:
      context: ./Caddy
    container_name: caddy
    depends_on:
      - lavalink
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddy:/etc/caddy
      - ./Caddy/Caddyfile.template:/etc/caddy/Caddyfile.template
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - EMAIL=${CADDY_EMAIL_INFO}
      - DOMAIN=${LAVALINK_DOMAIN}
    command: /bin/sh -c "envsubst < /etc/caddy/Caddyfile.template > /etc/caddy/Caddyfile && caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"

volumes:
  caddy_data:
  caddy_config:
